---
title: "PlotTraces.Rmd"
author: "Weihsueh Chiu"
date: "6/22/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
wd<-getwd()
library(ggplot2)
```

```{r get traces}

setwd("..")
source("CalciumFlux_peak_processing_functions_2016-11-30.R")
seq1.file.list<- get.seq1.file.list("seq1")
n.files<-length(seq1.file.list)

fnamesindx<-c(grep("1434",seq1.file.list)[1],
              grep("1082",seq1.file.list)[1],
              grep("1348",seq1.file.list)[1])
chemnum<-6

datlist<-list()
peak.parms.list<-list()
peak.parms.sum.list<-list()
df.list<-list()
for (j in 1:length(fnamesindx)) {
  dattmp<-get.oneplate.dat(seq1.file.list[fnamesindx[j]],print=TRUE)
  dattmp<-trim.oneplate.dat(dattmp)
  peak.parms.tmp<-
    get.onechem.peak.parms(dattmp,chemical.num=chemnum,upper=0.8,sdlim=1)
  peak.parms.tmp<-c(peak.parms.tmp,
                    get.onechem.peak.parms(dattmp,chemical.num=NA,upper=0.8,sdlim=1))
  peak.parms.sum.tmp<-summarize.peak.parms(peak.parms.tmp)
  df.list[[j]]<-data.frame()
  for (i in 1:length(peak.parms.tmp)) {
    df.tmp<-data.frame(t=peak.parms.tmp[[i]]$t,
                       y=peak.parms.tmp[[i]]$y)
    df.tmp$Well<-peak.parms.tmp[[i]]$rowcol
    df.tmp$Concentration<-peak.parms.tmp[[i]]$Chemical.Concentration
    df.tmp$Baseline<-peak.parms.sum.tmp$baseline[i]
    df.list[[j]]<-rbind(df.list[[j]],df.tmp)
  }
  df.list[[j]]$Donor<-peak.parms.tmp[[1]]$cellline
  datlist[[j]]<-dattmp 
  peak.parms.list[[j]]<-peak.parms.tmp
  peak.parms.sum.list[[j]]<-peak.parms.sum.tmp
}
setwd(wd)

```



```{r plot traces,fig.height=6,fig.width=2}
controlwell<-c("F13","K21","K13")
for (j in 1:3) {
  p<-ggplot(subset(df.list[[j]],Concentration>0 | Well==controlwell[j]),
            aes(x=t,y=y-Baseline))+
    geom_line(color="red")+facet_wrap(~Concentration,ncol=1)+xlim(0,20)+
    xlab("t (sec)")+ylab("RFU - Baseline")+theme_bw()+
    theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank())
  print(p)
  ggsave(paste("Disopyramide",
               df.list[[j]]$Donor[1],"Traces.pdf",sep="."
               ),
         p,height=6,width=2)
}
```

```{r plot closup one trace}
p<-ggplot(subset(df.list[[1]],Concentration == 10),
       aes(x=t,y=y)) + 
  geom_line(color="red")+
  xlim(1.25,7.5)+ylim(0,2000)+
    xlab("t (sec)")+ylab("RFU")+theme_bw()+
    theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank())
ggsave("OneTrace.pdf",p,height=1.5,width=2)
```

```{r plot traces together,fig.height=6,fig.width=6}
df.plotting<-rbind(subset(df.list[[1]],Concentration>0 | Well==controlwell[1]),
                   subset(df.list[[2]],Concentration>0 | Well==controlwell[2]),
                   subset(df.list[[3]],Concentration>0 | Well==controlwell[3]))
df.plotting$Donor <- factor(df.plotting$Donor,levels=c("1434","1348","1082"))
p<-ggplot(df.plotting,aes(x=t,y=y-Baseline))+
    geom_line(color="red")+
  facet_grid(Concentration~Donor)+
  xlim(0,20)+
    xlab("t (sec)")+ylab("RFU - Baseline")+theme_bw()+
    theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank())
  print(p)
  ggsave(paste("Disopyramide",
               paste(unique(df.plotting$Donor),collapse="."),
               "Traces.pdf",sep="."
               ),
         p,height=6,width=6)

```
