---
title: "In Vitro Observed Predicted_V2"
author: "Weihsueh Chiu"
date: "6/18/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(viridis)
# contains four objects: data.list,chemmap,
#   DR_Frame_All,DR_Frame_Controls, DR_Frame_Treated,
# created by source("MakeInVivoInVitrodata.R")
load("InVitrodatandpredictionSmall.Rdata")
celllines<-as.character(read.csv("Cell.lines.csv",as.is=TRUE)[,2])
names(celllines)<-1:length(celllines)
```

## Concentration-response plots by individual

```{r obs vs pred conc-response plots,fig.height=7,fig.width=7}
cols=c("CI"=magma(5)[4],
       "median"=magma(5)[3],
       "data"=magma(5)[1])
for (j in 1:nrow(chemmap)) {
  with(data.list[[j]], {
    p1<-ggplot(Prediction_Frame)+
      geom_ribbon(aes(x=concentration, ymin= p2.5, ymax= p97.5,
                      fill="CI"),color=NA)+
#      geom_point(aes(x=concentration, y=p50,color="median"))+
      geom_line(aes(x=concentration, y=p50,color="median"))+
      geom_point(data=DR_Frame, aes(x=Dose+1e-3, y=Response,color="data"))+
      xlab("Concentration (uM)")+
      ylab("Decay Rise Ratio")+
      scale_x_log10(breaks=c(0.001,0.1,1,10,100),
                    labels=c("C","0.1","1","10","100"))+
      #annotation_logticks(side="b",color="grey50") +
      coord_cartesian(xlim=c(1e-3,100))+
      ggtitle(paste(chemical.name,"Decay Rise Ratio"))+
      theme_bw()+theme(axis.text.x = element_text(angle = 90,vjust=0.5))+
      scale_fill_manual(name="",values=cols)+
      scale_color_manual(name="",values=cols)+
      guides(fill = guide_legend(override.aes = list(linetype = 0)),
         color = guide_legend(override.aes = list(linetype = 0)))+
      facet_wrap(~Individual, #scales = "free_y",
                 labeller = as_labeller(celllines))
    if (max(data.list[[j]]$Prediction_Frame$p97.5,
            data.list[[j]]$DR_Frame$Response) >= 10) {
      p1<-p1+scale_y_log10()+annotation_logticks(side="l",color="grey50")
    }
    print(p1)
    ggsave(paste(chemical.name,"InVitroObsPred.pdf",sep="."),p1,
           height=7,width=7.25,dpi=600)
  }
  )
}

```


This is a "randon sample" - so the "typical" error.

```{r obs vs pred scatter, fig.height=6,fig.width=6}

tmpframe<-rbind(DR_Frame_Treated,DR_Frame_Controls)

tmpframe$Chemical.name <- factor(tmpframe$Chemical.name,
                                 levels=c(chemmap$Chemical.name,
                                          unique(DR_Frame_Controls$Chemical.name)))
tmpframe$Donor <- celllines[tmpframe$Individual]

chemlevels<-levels(tmpframe$Chemical.name)
r2adj<-numeric()
chemlabel<-as.character(chemlevels)
for (j in 1:length(chemlabel)) {
  modsum<-summary(lm(log(Predicted)~log(Response),
           subset(tmpframe,Chemical.name==
                    chemlevels[j])))
  r2adj<-modsum$adj.r.squared
  sigerr<-modsum$sigma
  chemlabel[j]<-paste(chemlabel[j],"\n(R2=",signif(r2adj,2),
                      ",rse=",signif(sigerr,2),
                      ")",sep="")
}
names(chemlabel)<-chemlevels
tmpframe$ChemLabel<-factor(chemlabel[tmpframe$Chemical.name],
                           levels=chemlabel)

p1<-ggplot(tmpframe, 
             aes(x= Response, y=Predicted, 
                       fill=Donor))+
  geom_point(shape=21)+
  scale_x_log10()+
  scale_y_log10() +
  coord_cartesian(xlim=c(1,30),ylim=c(1,30)) +
  annotation_logticks() +
  theme(panel.grid.minor = element_blank())+
  xlab("In Vitro Observed")+
  ylab("Model Predicted")+
  geom_abline(intercept=0, slope=1, color="grey60")+
  geom_abline(intercept=0.5, slope=1, color="grey60", linetype="dashed")+
  geom_abline(intercept=-0.5, slope=1, color="grey60", linetype="dashed")+
  scale_fill_manual(name="",values=magma(27))+
  theme_bw()+
  facet_wrap(~ChemLabel)
ggsave("InVitroObsPredScatter.pdf",p1,
           height=7,width=7.25,dpi=600)
ggsave("InVitroObsPredScatter.jpg",p1, device="jpg",
           height=7,width=7.25,dpi=600)
```

